### ISSUE TITLE
ValueError: offset must be non-negative and no greater than buffer length (59260)

### ISSUE THREAD

**Issue by songwanguw** [microsoft/ProphetNet#9]
fairseq-generate $DATA_DIR --path $CHECK_POINT --user-dir prophetnet --task translation_prophetnet --batch-size 16 --gen-subset test --beam $BEAM --num-workers 4  --min-len 16  --max-len-b 120 --no-repeat-ngram-size 3 --lenpen $LENPEN 2>&1 > $OUTPUT_FILE
  0%|                                                                                            | 0/15 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq==0.9.0', 'console_scripts', 'fairseq-generate')()
  File "/opt/conda/lib/python3.7/site-packages/fairseq_cli/generate.py", line 199, in cli_main
    main(args)
  File "/opt/conda/lib/python3.7/site-packages/fairseq_cli/generate.py", line 94, in main
    for sample in t:
  File "/opt/conda/lib/python3.7/site-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.7/site-packages/fairseq/data/iterators.py", line 36, in __iter__
    for x in self.iterable:
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/fairseq/data/language_pair_dataset.py", line 183, in __getitem__
    tgt_item = self.tgt[index] if self.tgt is not None else None
  File "/opt/conda/lib/python3.7/site-packages/fairseq/data/indexed_dataset.py", line 475, in __getitem__
    np_array = np.frombuffer(self._bin_buffer, dtype=self._index.dtype, count=size, offset=ptr)
ValueError: offset must be non-negative and no greater than buffer length (59260)

**Comment by wying8349** [comment]
Hello, I am seeing a similar error as you report here. Are you willing to share how did you overcome it?
Thank you!

**Comment by yasong** [comment]
Check if there is any residue of the last running process and try to kill it.

**Comment by INDRA-JETHANI** [comment]
Did it solve the problem
